# Generated by Django 3.2.8 on 2024-03-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('username2', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('text', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('username2', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
