# Generated by Django 3.2.8 on 2024-03-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_message_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='username1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='relation',
            name='username2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
